# SPDX-License-Identifier: Apache-2.0
"""Fixed-base AgileX Nero arm primitive (MuJoCo Native backend).

The sim layer (``sim/bridge/bridge_node.py``) owns the physics loop AND the
ROS topics. This primitive is the thin Robonix boot-layer wrapper that:

    on_init       — validate config, cache for activate.
    on_activate   — spawn ``sim/start.sh``, wait for the first
                    ``/joint_states`` as proof the sim is up, then declare the
                    three ROS 2 data topics on Atlas (joint_states /
                    joint_command / end_pose). ``arm/driver`` is auto-declared
                    by the framework lifecycle servicer.
    on_deactivate — kill the sim subprocess (process group).
    on_shutdown   — last-chance kill (idempotent with on_deactivate).

The rpc capabilities (status / set_enabled / emergency_stop / move_home /
follow_joint_trajectory) are exposed as MCP tools that call the bridge's ROS
services / actions, so plans gate, recover and move the simulated arm through
the same capability graph they use for a real arm.

Config (from the deploy manifest's ``primitive[].config`` block, delivered via
``Driver(CMD_INIT, config_json)``):

    joint_states_topic       default "/joint_states"
    joint_command_topic      default "/joint_command"
    end_pose_topic           default "/feedback/tcp_pose"
    object_pose_topic        default "/feedback/object_pose"
    arm_controller_action    default "/arm_controller/follow_joint_trajectory"
    gripper_controller_action default "/gripper_controller/follow_joint_trajectory"
    sentinel_timeout_s       default 30.0
    viewer                   default false      — open a mujoco.viewer window
    sim_python               default ""         — override the sim interpreter
                             (passed through as NERO_PYTHON to sim/start.sh)
    move_home_on_activate    default true       — call /move_home once right
                             after activation, so the arm starts at
                             NeroMujocoController.move_home()'s target pose
                             instead of the sim's raw zero qpos.
"""
from __future__ import annotations

import logging
import os
import signal
import subprocess
import sys
import threading
import time
from pathlib import Path
from typing import Any, Optional

from robonix_api import Err, Ok

from nero_arm_provider import nero_arm

# Generated by `rbnx codegen --mcp` during scripts/build.sh (see start.sh for
# the PYTHONPATH entry that makes this importable).
from nero_arm_mcp import (  # type: ignore[import-not-found]
    EmergencyStop_Request,
    EmergencyStop_Response,
    FollowJointTrajectory_Request,
    FollowJointTrajectory_Response,
    GetStatus_Request,
    GetStatus_Response,
    MoveHome_Request,
    MoveHome_Response,
    Pick_Request,
    Pick_Response,
    SetEnabled_Request,
    SetEnabled_Response,
)

logging.basicConfig(
    level=os.environ.get("NERO_ARM_LOG_LEVEL", "INFO"),
    format="[nero_arm] %(message)s",
)
log = logging.getLogger("nero_arm")

_PKG_ROOT = Path(__file__).resolve().parent.parent      # primitives/nero_arm
_REPO_ROOT = _PKG_ROOT.parent.parent                    # package repo root (sim/, assets/)

# sim/native/pick_planner.py — pure geometry, no rclpy import (see its
# docstring for why). Made importable the same way sim/bridge imports
# native.*: put the sim/ package dir on sys.path.
if str(_REPO_ROOT / "sim") not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT / "sim"))
from native import pick_planner  # noqa: E402

# Joint name sets the bridge's FollowJointTrajectory servers expect. Kept in
# sync with sim/bridge/bridge_node.py and sim/native/controller.py; they select
# which action (arm vs gripper) a follow_joint_trajectory goal is sent to.
ARM_JOINT_NAMES = tuple(f"joint{i}" for i in range(1, 8))   # joint1..joint7
GRIPPER_JOINT_NAMES = ("gripper_joint1", "gripper_joint2")

# Sim subprocess + cached cfg. Allocated in on_activate, released in
# on_deactivate / on_shutdown.
_sim_proc: Optional[subprocess.Popen] = None
_sim_pgid: Optional[int] = None
_resolved_cfg: dict[str, Any] = {}

# Live feedback mirror for the `status` MCP tool, fed by the persistent
# /joint_states subscription set up in on_activate.
_joint_state_sub: Optional[Any] = None
_first_joint_state = threading.Event()
_state_lock = threading.Lock()
_latest_state: tuple[list[float], float, float] | None = None  # (joints_rad, width_m, ts)
_control_enabled = True

# Live mirror of /feedback/object_pose for the `pick` MCP tool, fed by a
# persistent subscription set up in on_activate (best-effort: absent when the
# sim loads the bare-arm model, so `pick` fails with a clear detail rather
# than hanging when this stays None).
_object_pose_sub: Optional[Any] = None
_object_pose_lock = threading.Lock()
_latest_object_pose: tuple[float, float, float, float] | None = None  # (x, y, z, ts)

# Persistent ROS service clients, keyed by (srv_type, name). Clients are
# deliberately never destroyed: with rmw_fastrtps_cpp, an explicit
# `destroy_client()` right before `rclpy.shutdown()` leaves Fast DDS's async
# entity-teardown threads mid-flight and the interpreter aborts
# ("terminate called without an active exception", exit 134). Reusing one
# client per service and letting node destruction reclaim them exits cleanly.
_service_clients: dict[tuple[type, str], Any] = {}

# Persistent ROS action clients, keyed by (action_type, name). Same lifetime
# reasoning as _service_clients: never destroy explicitly before shutdown.
_action_clients: dict[tuple[type, str], Any] = {}


def _on_joint_state(msg) -> None:
    """Record the latest /joint_states and mark the sentinel as seen."""
    global _latest_state
    names = list(msg.name)
    positions = list(msg.position)
    joints_rad: list[float] = []
    width_m = 0.0
    for name, pos in zip(names, positions):
        if name == "gripper":
            width_m = float(pos)
        else:
            joints_rad.append(float(pos))
    with _state_lock:
        _latest_state = (joints_rad, width_m, time.monotonic())
    _first_joint_state.set()


def _on_object_pose(msg) -> None:
    """Record the latest /feedback/object_pose (geometry_msgs/PoseStamped)."""
    global _latest_object_pose
    p = msg.pose.position
    with _object_pose_lock:
        _latest_object_pose = (float(p.x), float(p.y), float(p.z), time.monotonic())


# ── sim subprocess helpers ────────────────────────────────────────────────
def _spawn_sim(cfg: dict[str, Any]) -> None:
    """Launch sim/start.sh as its own session so we can signal the whole group."""
    global _sim_proc, _sim_pgid
    argv = ["bash", str(_REPO_ROOT / "sim" / "start.sh")]
    if bool(cfg.get("viewer", False)):
        argv.append("--viewer")
    env = dict(os.environ)
    sim_python = str(cfg.get("sim_python", "")).strip()
    if sim_python:
        env["NERO_PYTHON"] = sim_python
    log_path = _PKG_ROOT / "rbnx-build" / "data" / "nero_sim.log"
    log_path.parent.mkdir(parents=True, exist_ok=True)
    log_fh = open(log_path, "ab", buffering=0)
    log.info("spawning sim (viewer=%s) -> %s",
             bool(cfg.get("viewer", False)), log_path)
    _sim_proc = subprocess.Popen(
        argv, stdout=log_fh, stderr=log_fh, env=env, start_new_session=True,
    )
    _sim_pgid = os.getpgid(_sim_proc.pid)


def _kill_sim() -> None:
    """Tear down the sim process group. Idempotent (safe from on_deactivate
    followed by on_shutdown)."""
    global _sim_proc, _sim_pgid
    pgid = _sim_pgid
    if pgid is None and _sim_proc is not None:
        try:
            pgid = os.getpgid(_sim_proc.pid)
        except ProcessLookupError:
            pgid = None
    if pgid is None:
        _sim_proc = None
        _sim_pgid = None
        return

    try:
        os.killpg(pgid, signal.SIGTERM)
    except ProcessLookupError:
        _sim_proc = None
        _sim_pgid = None
        return

    deadline = time.monotonic() + 5.0
    while time.monotonic() < deadline:
        try:
            os.killpg(pgid, 0)
        except ProcessLookupError:
            _sim_proc = None
            _sim_pgid = None
            return
        time.sleep(0.1)

    try:
        os.killpg(pgid, signal.SIGKILL)
    except ProcessLookupError:
        pass
    if _sim_proc is not None:
        try:
            _sim_proc.wait(timeout=1.0)
        except subprocess.TimeoutExpired:
            pass
    _sim_proc = None
    _sim_pgid = None


def _wait_for_joint_states(topic: str, timeout_s: float) -> bool:
    """Subscribe (RELIABLE) to `topic` and block until the first message.

    The bridge publishes with rclpy's default depth=1 RELIABLE QoS, so a
    best-effort subscription would not match. The subscription is kept after
    the wait to feed the `status` tool.
    """
    global _joint_state_sub
    from robonix_api.ros import RosBackend
    from sensor_msgs.msg import JointState

    backend = RosBackend.get()
    # Re-activation: drop any previous subscription before resubscribing.
    if _joint_state_sub is not None:
        try:
            backend.node.destroy_subscription(_joint_state_sub)
        except Exception:  # noqa: BLE001
            pass
        _joint_state_sub = None
    _first_joint_state.clear()
    _joint_state_sub = backend.create_subscription(
        JointState, topic, _on_joint_state, qos="reliable",
    )
    log.info("waiting for first JointState on %s — up to %.1fs", topic, timeout_s)
    return _first_joint_state.wait(timeout_s)


# ── ROS service helper (for MCP tools → bridge services) ──────────────────
def _call_bridge_service(srv_type, name: str, request):
    """Synchronous call to a bridge service via the shared RosBackend node.

    Returns the response message, or None if the service is unavailable or the
    call times out. Safe to call from the MCP server thread: the RosBackend
    executor runs on its own thread and completes the future.

    Clients are cached (never destroyed) — see the note on ``_service_clients``
    for why an explicit destroy_client would abort the process at shutdown.
    """
    from robonix_api.ros import RosBackend

    node = RosBackend.get().node
    key = (srv_type, name)
    client = _service_clients.get(key)
    if client is None:
        client = node.create_client(srv_type, name)
        _service_clients[key] = client

    try:
        if not client.wait_for_service(timeout_sec=2.0):
            return None
        future = client.call_async(request)
        # rclpy Future.result() takes no timeout argument, so poll done() with
        # a bounded wait while the RosBackend executor completes the call.
        deadline = time.monotonic() + 3.0
        while not future.done() and time.monotonic() < deadline:
            time.sleep(0.05)
        if not future.done():
            future.cancel()
            return None
        return future.result()
    except Exception:  # noqa: BLE001
        return None


# ── ROS action helper (for MCP tools → bridge FollowJointTrajectory) ──────
def _call_bridge_action(action_type, name: str, goal, timeout_s: float = 30.0):
    """Send one action goal via the shared RosBackend node and block for its
    terminal result.

    Returns ``(result, err)`` where ``result`` is the action Result message on
    success and ``None`` otherwise; ``err`` is a human-readable reason. Safe to
    call from the MCP server thread: the RosBackend MultiThreadedExecutor
    completes the futures while this thread polls.

    Clients are cached (never destroyed) — see the note on ``_service_clients``.
    """
    from rclpy.action import ActionClient
    from robonix_api.ros import RosBackend

    node = RosBackend.get().node
    key = (action_type, name)
    client = _action_clients.get(key)
    if client is None:
        client = ActionClient(node, action_type, name)
        _action_clients[key] = client

    if not client.wait_for_server(timeout_sec=2.0):
        return None, f"action server {name} not available"

    goal_future = client.send_goal_async(goal)
    deadline = time.monotonic() + 3.0
    while not goal_future.done() and time.monotonic() < deadline:
        time.sleep(0.05)
    if not goal_future.done():
        goal_future.cancel()
        return None, "goal acceptance timed out"
    goal_handle = goal_future.result()
    if goal_handle is None or not getattr(goal_handle, "accepted", False):
        return None, "goal rejected (joint-name or trajectory mismatch)"

    result_future = goal_handle.get_result_async()
    deadline = time.monotonic() + timeout_s
    while not result_future.done() and time.monotonic() < deadline:
        time.sleep(0.05)
    if not result_future.done():
        # The server keeps pacing the rest of the trajectory; the sim is
        # transient so there is no need to cancel explicitly.
        return None, f"trajectory execution timed out after {timeout_s:.0f}s"
    return result_future.result().result, ""


def _mcp_traj_to_ros(traj):
    """``trajectory_msgs_mcp.JointTrajectory`` -> rclpy ``trajectory_msgs/JointTrajectory``."""
    from builtin_interfaces.msg import Duration
    from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint

    ros = JointTrajectory()
    ros.joint_names = list(traj.joint_names)
    for p in traj.points:
        pt = JointTrajectoryPoint()
        pt.positions = [float(x) for x in p.positions]
        pt.velocities = [float(x) for x in p.velocities]
        pt.accelerations = [float(x) for x in p.accelerations]
        pt.effort = [float(x) for x in p.effort]
        d = p.time_from_start
        pt.time_from_start = Duration(sec=int(d.sec), nanosec=int(d.nanosec))
        ros.points.append(pt)
    return ros


def _read_arm_rad() -> list[float]:
    """Measured joint1..joint7 positions (rad), or [] before the first state."""
    with _state_lock:
        state = _latest_state
    return [] if state is None else list(state[0])


def _read_gripper_width() -> float | None:
    """Measured gripper width (m), or None before the first /joint_states."""
    with _state_lock:
        state = _latest_state
    return None if state is None else state[1]


def _wait_gripper_width(target: float, timeout: float, tol: float = 0.005) -> bool:
    """Poll /joint_states until the gripper width reaches `target` (within
    `tol`). Returns True once opened, False on timeout. The overdamped gripper
    approaches the target asymptotically, so `tol` stops us from waiting on the
    last fraction of a millimetre that never quite lands."""
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        width = _read_gripper_width()
        if width is not None and width >= target - tol:
            return True
        time.sleep(0.1)
    return False


def _wait_arm_joints(targets: dict[str, float], timeout: float, tol: float = 0.08) -> bool:
    """Poll /joint_states until every arm joint is within `tol` of its target.

    The arm's position servo has no integral term, so it settles to a small
    steady-state offset (heaviest at the wrist) and never exactly reaches a
    commanded pose; `tol` (rad, per-joint) stops us from hanging on that offset.
    This mirrors `_wait_gripper_width`: the FollowJointTrajectory action reports
    success as soon as it applies the target, not when the arm physically
    arrives, so without this wait the close can fire while the wrist is still
    mid-swing and the fingers miss the object."""
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        joints = _read_arm_rad()
        if len(joints) == len(ARM_JOINT_NAMES) and all(
            abs(joints[i] - targets[n]) <= tol for i, n in enumerate(ARM_JOINT_NAMES)
        ):
            return True
        time.sleep(0.1)
    return False


# ── lifecycle handlers ────────────────────────────────────────────────────
@nero_arm.on_init
def on_init(cfg: dict) -> Any:
    """REGISTERED → INACTIVE. Validate config; heavy work waits for on_activate
    so a DEACTIVATE → ACTIVATE cycle starts from a clean state."""
    global _resolved_cfg
    cfg = dict(cfg or {})
    try:
        timeout = float(cfg.get("sentinel_timeout_s", 30.0))
        if timeout <= 0:
            return Err(f"sentinel_timeout_s must be > 0, got {timeout}")
    except (TypeError, ValueError) as exc:
        return Err(f"sentinel_timeout_s not numeric: {exc}")
    _resolved_cfg = cfg
    log.info(
        "CMD_INIT ok (joint_states=%s, joint_command=%s, end_pose=%s, "
        "object_pose=%s, viewer=%s)",
        cfg.get("joint_states_topic", "/joint_states"),
        cfg.get("joint_command_topic", "/joint_command"),
        cfg.get("end_pose_topic", "/feedback/tcp_pose"),
        cfg.get("object_pose_topic", "/feedback/object_pose"),
        bool(cfg.get("viewer", False)),
    )
    return Ok()


@nero_arm.on_activate
def on_activate() -> Any:
    """INACTIVE → ACTIVE. Spawn the sim, prove the bridge is up, declare topics."""
    cfg = _resolved_cfg or {}
    joint_states_topic = str(cfg.get("joint_states_topic", "/joint_states"))
    joint_command_topic = str(cfg.get("joint_command_topic", "/joint_command"))
    end_pose_topic = str(cfg.get("end_pose_topic", "/feedback/tcp_pose"))
    object_pose_topic = str(cfg.get("object_pose_topic", "/feedback/object_pose"))
    sentinel_timeout = float(cfg.get("sentinel_timeout_s", 30.0))

    try:
        _spawn_sim(cfg)
    except Exception as exc:  # noqa: BLE001
        return Err(f"spawn sim failed: {exc}")

    if not _wait_for_joint_states(joint_states_topic, sentinel_timeout):
        _kill_sim()
        return Err(
            f"no JointState on {joint_states_topic} within {sentinel_timeout:.1f}s "
            f"(check {_PKG_ROOT / 'rbnx-build' / 'data' / 'nero_sim.log'}; is "
            f"the MuJoCo model loadable and the bridge python on PATH?)"
        )

    try:
        nero_arm.declare_ros2_topic(
            "robonix/primitive/arm/joint_states",
            topic=joint_states_topic,
            qos="reliable",
            description=(
                "Measured Nero arm joint feedback (sensor_msgs/JointState, "
                "joint1..joint7 + gripper width). Frame-free joint space."
            ),
        )
        # joint_command is topic_in (the bridge subscribes; consumers publish).
        nero_arm.declare_ros2_topic(
            "robonix/primitive/arm/joint_command",
            topic=joint_command_topic,
            qos="reliable",
            description=(
                "Named joint target (sensor_msgs/JointState). PUBLISH here to "
                "drive the arm in joint space; a `gripper` entry commands the "
                "finger opening in metres."
            ),
        )
        nero_arm.declare_ros2_topic(
            "robonix/primitive/arm/end_pose",
            topic=end_pose_topic,
            qos="reliable",
            description=(
                "End-effector pose (geometry_msgs/Pose) of the finger midpoint "
                "oriented like link7. Frame: base_link."
            ),
        )
        nero_arm.declare_ros2_topic(
            "robonix/primitive/arm/object_pose",
            topic=object_pose_topic,
            qos="reliable",
            description=(
                "Grasp-target object pose (geometry_msgs/PoseStamped) from the "
                "tabletop scene, frame `world` (== base_link). Absent when the "
                "sim loads the bare-arm model."
            ),
        )
    except Exception as exc:  # noqa: BLE001
        _kill_sim()
        return Err(f"declare_ros2_topic failed: {exc}")

    # Subscribe to object_pose for the `pick` tool's default-target lookup.
    # Best-effort: the bare-arm model has no `object` body, so the bridge
    # never publishes here — that is not an activation failure, `pick` just
    # reports it can't find an object pose when called.
    global _object_pose_sub
    try:
        from robonix_api.ros import RosBackend
        from geometry_msgs.msg import PoseStamped

        backend = RosBackend.get()
        if _object_pose_sub is not None:
            try:
                backend.node.destroy_subscription(_object_pose_sub)
            except Exception:  # noqa: BLE001
                pass
            _object_pose_sub = None
        _object_pose_sub = backend.create_subscription(
            PoseStamped, object_pose_topic, _on_object_pose, qos="reliable",
        )
    except Exception as exc:  # noqa: BLE001
        log.warning("could not subscribe to object_pose (%s); "
                    "pick will require explicit x/y/z", exc)

    if bool(cfg.get("move_home_on_activate", True)):
        from std_srvs.srv import Empty

        resp = _call_bridge_service(Empty, "/move_home", Empty.Request())
        if resp is None:
            log.warning("move_home_on_activate: /move_home service unavailable, "
                        "arm stays at the sim's raw zero pose")
        else:
            log.info("move_home_on_activate: sent /move_home")

    log.info(
        "CMD_ACTIVATE ok: joint_states=%s joint_command=%s end_pose=%s object_pose=%s",
        joint_states_topic, joint_command_topic, end_pose_topic, object_pose_topic,
    )
    return Ok()


@nero_arm.on_deactivate
def on_deactivate() -> Any:
    """ACTIVE → INACTIVE. Kill the sim and drop the feedback subscriptions."""
    _kill_sim()
    global _joint_state_sub, _object_pose_sub
    if _joint_state_sub is not None:
        try:
            from robonix_api.ros import RosBackend
            RosBackend.get().node.destroy_subscription(_joint_state_sub)
        except Exception:  # noqa: BLE001
            pass
        _joint_state_sub = None
    if _object_pose_sub is not None:
        try:
            from robonix_api.ros import RosBackend
            RosBackend.get().node.destroy_subscription(_object_pose_sub)
        except Exception:  # noqa: BLE001
            pass
        _object_pose_sub = None
    log.info("CMD_DEACTIVATE ok")
    return Ok()


@nero_arm.on_shutdown
def on_shutdown() -> Any:
    """any → TERMINATED. Last-chance kill. Idempotent with on_deactivate."""
    _kill_sim()
    # Shut down the process-wide rclpy backend so the interpreter can exit
    # cleanly (avoids the rmw/rcl `std::terminate` abort on process exit).
    try:
        from robonix_api.ros import RosBackend
        RosBackend.get().shutdown()
    except Exception:  # noqa: BLE001
        pass
    return Ok()


# ── MCP rpc tools ─────────────────────────────────────────────────────────
@nero_arm.mcp("robonix/primitive/arm/status")
def status(_req: GetStatus_Request) -> GetStatus_Response:
    """Read the simulated Nero arm's connection, enable, joint and gripper state
    without moving it. `connected` reflects whether /joint_states arrived
    recently; `enabled` mirrors the bridge's control gate."""
    with _state_lock:
        state = _latest_state
        enabled = _control_enabled
    if state is None:
        return GetStatus_Response(
            connected=False, enabled=enabled, arm="nero_arm",
            joints_rad=[], gripper_width_m=0.0,
            detail="no joint state received yet",
        )
    joints_rad, width_m, ts = state
    connected = (time.monotonic() - ts) < 1.0
    return GetStatus_Response(
        connected=connected,
        enabled=enabled,
        arm="nero_arm",
        joints_rad=list(joints_rad),
        gripper_width_m=width_m,
        detail="ok" if connected else "no recent joint state",
    )


@nero_arm.mcp("robonix/primitive/arm/set_enabled")
def set_enabled(req: SetEnabled_Request) -> SetEnabled_Response:
    """Open or close the simulated arm's control gate. While disabled, the
    bridge ignores /joint_command and /control/move_j."""
    global _control_enabled
    from std_srvs.srv import SetBool

    resp = _call_bridge_service(SetBool, "/control_enable", SetBool.Request(data=bool(req.enabled)))
    if resp is None or not resp.success:
        return SetEnabled_Response(
            success=False, enabled=_control_enabled, arm="nero_arm",
            detail="bridge /control_enable service unavailable or failed",
        )
    _control_enabled = bool(req.enabled)
    return SetEnabled_Response(
        success=True, enabled=_control_enabled, arm="nero_arm",
        detail=f"control gate {'opened' if _control_enabled else 'closed'}",
    )


@nero_arm.mcp("robonix/primitive/arm/emergency_stop")
def emergency_stop(_req: EmergencyStop_Request) -> EmergencyStop_Response:
    """Immediately hold the simulated arm at its current pose and close the
    control gate. Always allowed."""
    global _control_enabled
    from std_srvs.srv import Empty

    resp = _call_bridge_service(Empty, "/emergency_stop", Empty.Request())
    if resp is None:
        return EmergencyStop_Response(
            success=False, arm="nero_arm", detail="bridge /emergency_stop service unavailable",
        )
    _control_enabled = False
    return EmergencyStop_Response(success=True, arm="nero_arm", detail="emergency stop sent")


@nero_arm.mcp("robonix/primitive/arm/move_home")
def move_home(_req: MoveHome_Request) -> MoveHome_Response:
    """Command the simulated arm back to its zero (home) joint pose."""
    from std_srvs.srv import Empty

    resp = _call_bridge_service(Empty, "/move_home", Empty.Request())
    if resp is None:
        return MoveHome_Response(
            success=False, arm="nero_arm", detail="bridge /move_home service unavailable",
        )
    return MoveHome_Response(success=True, arm="nero_arm", detail="move home sent")


@nero_arm.mcp("robonix/primitive/arm/follow_joint_trajectory")
def follow_joint_trajectory(req: FollowJointTrajectory_Request) -> FollowJointTrajectory_Response:
    """Execute a timed joint trajectory through the bridge's FollowJointTrajectory
    action (the standard MoveIt execution interface). `trajectory.joint_names`
    selects the controller: joint1..joint7 -> the arm controller,
    gripper_joint1/gripper_joint2 -> the gripper controller. Success means the
    final point was commanded; the overdamped arm may still be settling, so read
    joint_states for the true pose. `final_joints_rad` is the measured
    joint1..joint7 pose after the call."""
    from control_msgs.action import FollowJointTrajectory as FollowJT

    traj = getattr(req, "trajectory", None)
    if traj is None or not getattr(traj, "points", None):
        return FollowJointTrajectory_Response(
            success=False, arm="nero_arm", final_joints_rad=[],
            detail="empty trajectory",
        )

    names = list(traj.joint_names)
    cfg = _resolved_cfg or {}
    if set(names) == set(ARM_JOINT_NAMES):
        action_name = str(cfg.get(
            "arm_controller_action", "/arm_controller/follow_joint_trajectory"))
    elif set(names) == set(GRIPPER_JOINT_NAMES):
        action_name = str(cfg.get(
            "gripper_controller_action", "/gripper_controller/follow_joint_trajectory"))
    else:
        return FollowJointTrajectory_Response(
            success=False, arm="nero_arm", final_joints_rad=[],
            detail=(
                f"joint_names {names} match neither arm {list(ARM_JOINT_NAMES)} "
                f"nor gripper {list(GRIPPER_JOINT_NAMES)}"
            ),
        )

    goal = FollowJT.Goal()
    goal.trajectory = _mcp_traj_to_ros(traj)
    result, err = _call_bridge_action(FollowJT, action_name, goal)
    if result is None:
        return FollowJointTrajectory_Response(
            success=False, arm="nero_arm", final_joints_rad=_read_arm_rad(),
            detail=err,
        )

    ok = result.error_code == FollowJT.Result.SUCCESSFUL
    detail = "ok" if ok else f"error_code={result.error_code} {result.error_string}".strip()
    return FollowJointTrajectory_Response(
        success=ok, arm="nero_arm", final_joints_rad=_read_arm_rad(),
        detail=detail,
    )


# ── pick (top-down, MoveIt compute_ik + FollowJointTrajectory) ────────────
def _compute_ik(x: float, y: float, z: float, seed: dict[str, float]) -> Optional[dict[str, float]]:
    """One /compute_ik call: flange pointing straight down at (x, y, z), from
    `seed`. Returns {jointN: rad} on success, None on failure/unavailable."""
    from moveit_msgs.msg import RobotState
    from moveit_msgs.srv import GetPositionIK
    from geometry_msgs.msg import PoseStamped

    quat = pick_planner.straight_down_quat()
    req = GetPositionIK.Request()
    req.ik_request.group_name = "arm"
    rs = RobotState()
    rs.joint_state.name = list(seed.keys())
    rs.joint_state.position = list(seed.values())
    req.ik_request.robot_state = rs
    req.ik_request.avoid_collisions = True
    req.ik_request.timeout.sec = 3
    pose = PoseStamped()
    pose.header.frame_id = "base_link"
    pose.pose.position.x, pose.pose.position.y, pose.pose.position.z = x, y, z
    (pose.pose.orientation.x, pose.pose.orientation.y,
     pose.pose.orientation.z, pose.pose.orientation.w) = quat
    req.ik_request.pose_stamped = pose
    req.ik_request.ik_link_name = "gripper_flange"

    resp = _call_bridge_service(GetPositionIK, "/compute_ik", req)
    if resp is None or resp.error_code.val != 1:  # MoveItErrorCodes.SUCCESS
        return None
    return {n: p for n, p in zip(resp.solution.joint_state.name, resp.solution.joint_state.position)
            if n in ARM_JOINT_NAMES}


def _execute_arm_move(joints: dict[str, float], seconds: float = 2.0) -> tuple[bool, str]:
    """One FollowJointTrajectory point on the arm controller."""
    from control_msgs.action import FollowJointTrajectory as FollowJT
    from builtin_interfaces.msg import Duration
    from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint

    action_name = str((_resolved_cfg or {}).get(
        "arm_controller_action", "/arm_controller/follow_joint_trajectory"))
    traj = JointTrajectory()
    traj.joint_names = list(ARM_JOINT_NAMES)
    pt = JointTrajectoryPoint()
    pt.positions = [joints[n] for n in ARM_JOINT_NAMES]
    pt.time_from_start = Duration(sec=int(seconds), nanosec=0)
    traj.points = [pt]
    goal = FollowJT.Goal()
    goal.trajectory = traj
    result, err = _call_bridge_action(FollowJT, action_name, goal)
    if result is None:
        return False, err
    ok = result.error_code == FollowJT.Result.SUCCESSFUL
    return ok, ("ok" if ok else f"error_code={result.error_code} {result.error_string}".strip())


def _execute_gripper_move(width: float, seconds: float = 2.0) -> tuple[bool, str]:
    """One FollowJointTrajectory point on the gripper controller. `width` is
    the single-opening value (metres); folded into the mirrored
    gripper_joint1/gripper_joint2 pair the action expects."""
    from control_msgs.action import FollowJointTrajectory as FollowJT
    from builtin_interfaces.msg import Duration
    from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint

    action_name = str((_resolved_cfg or {}).get(
        "gripper_controller_action", "/gripper_controller/follow_joint_trajectory"))
    half = width / 2.0
    traj = JointTrajectory()
    traj.joint_names = list(GRIPPER_JOINT_NAMES)
    pt = JointTrajectoryPoint()
    pt.positions = [half, -half]
    pt.time_from_start = Duration(sec=int(seconds), nanosec=0)
    traj.points = [pt]
    goal = FollowJT.Goal()
    goal.trajectory = traj
    result, err = _call_bridge_action(FollowJT, action_name, goal)
    if result is None:
        return False, err
    ok = result.error_code == FollowJT.Result.SUCCESSFUL
    return ok, ("ok" if ok else f"error_code={result.error_code} {result.error_string}".strip())


@nero_arm.mcp("robonix/primitive/arm/pick")
def pick(req: Pick_Request) -> Pick_Response:
    """Top-down pick: approach above the object -> descend -> close the
    gripper -> lift. Plans each waypoint with MoveIt's `compute_ik` (KDL) and
    executes through the bridge's FollowJointTrajectory actions — the same
    execution path `follow_joint_trajectory` uses.

    x/y/z (`has_x`/`has_y`/`has_z`) default to the most recent
    `/feedback/object_pose` reading when omitted; fails with a clear detail if
    none has arrived (bare-arm model, or no scene loaded yet).

    Requires `move_group` running (needs `/compute_ik`); fails with a clear
    detail rather than hanging or crashing if it is not.

    The runtime adds flat, collision-only contact pads to the fingers' grasping
    face so the pinch is a face-to-face grip that holds through the lift (see
    sim/native/runtime.py FINGER_PAD_*). This tool does not retry or detect a
    mid-lift drop (read `object_pose` after the call to check)."""
    with _object_pose_lock:
        observed = _latest_object_pose

    x = float(req.x) if getattr(req, "has_x", False) else (observed[0] if observed else None)
    y = float(req.y) if getattr(req, "has_y", False) else (observed[1] if observed else None)
    z = float(req.z) if getattr(req, "has_z", False) else (observed[2] if observed else None)
    if x is None or y is None or z is None:
        return Pick_Response(
            success=False, arm="nero_arm", final_joints_rad=_read_arm_rad(),
            detail="no object pose available (pass x/y/z, or wait for /feedback/object_pose)",
        )

    targets = pick_planner.sequence_targets(x, y, z)

    seed = dict(pick_planner.IK_SEED)
    solutions: dict[str, dict[str, float]] = {}
    for phase in ("approach", "descend", "lift"):
        tx, ty, tz = targets[phase]
        sol = _compute_ik(tx, ty, tz, seed)
        if sol is None:
            return Pick_Response(
                success=False, arm="nero_arm", final_joints_rad=_read_arm_rad(),
                detail=f"compute_ik failed for phase '{phase}' at ({tx:.3f},{ty:.3f},{tz:.3f}); "
                       f"is move_group running?",
            )
        solutions[phase] = sol
        seed = sol  # chain: each solve seeds the next for a continuous path

    # Open the gripper FIRST and wait until the fingers actually reach the open
    # width before moving the arm. The overdamped gripper opens slowly, so
    # commanding the open after the approach leaves it barely open (well under
    # the object width) by the time the close lands — the fingers then can't get
    # around the object and the grasp misses.
    ok, detail = _execute_gripper_move(pick_planner.GRIPPER_OPEN_WIDTH)
    if not ok:
        return Pick_Response(success=False, arm="nero_arm", final_joints_rad=_read_arm_rad(),
                             detail=f"gripper open failed: {detail}")
    if not _wait_gripper_width(pick_planner.GRIPPER_OPEN_WIDTH, timeout=15.0):
        width = _read_gripper_width()
        return Pick_Response(
            success=False, arm="nero_arm", final_joints_rad=_read_arm_rad(),
            detail=f"gripper did not open to {pick_planner.GRIPPER_OPEN_WIDTH:.3f}m "
                   f"(measured {width if width is not None else float('nan'):.3f}m) in time",
        )

    ok, detail = _execute_arm_move(solutions["approach"])
    if not ok:
        return Pick_Response(success=False, arm="nero_arm", final_joints_rad=_read_arm_rad(),
                             detail=f"approach move failed: {detail}")
    if not _wait_arm_joints(solutions["approach"], timeout=10.0):
        return Pick_Response(
            success=False, arm="nero_arm", final_joints_rad=_read_arm_rad(),
            detail="arm did not reach the approach pose in time",
        )

    ok, detail = _execute_arm_move(solutions["descend"])
    if not ok:
        return Pick_Response(success=False, arm="nero_arm", final_joints_rad=_read_arm_rad(),
                             detail=f"descend move failed: {detail}")
    if not _wait_arm_joints(solutions["descend"], timeout=10.0):
        return Pick_Response(
            success=False, arm="nero_arm", final_joints_rad=_read_arm_rad(),
            detail="arm did not reach the descend pose in time (fingers may miss the object)",
        )

    ok, detail = _execute_gripper_move(0.0)
    if not ok:
        return Pick_Response(success=False, arm="nero_arm", final_joints_rad=_read_arm_rad(),
                             detail=f"gripper close failed: {detail}")

    ok, detail = _execute_arm_move(solutions["lift"])
    return Pick_Response(
        success=ok, arm="nero_arm", final_joints_rad=_read_arm_rad(),
        detail=("ok — read object_pose to confirm the grasp held" if ok
                else f"lift move failed: {detail}"),
    )


if __name__ == "__main__":
    nero_arm.run()
